export enum Subject {
  NORWEGIAN = "Norsk",
  NEWNORWEGIAN = "Nynorsk",
  MATHEMATICS = "Matematikk",
  ENGLISH = "Engelsk",
  NATURAL_SCIENCE = "Naturfag",
  SOCIAL_STUDIES = "Samfunnsfag",
  ART = "Kunst og håndverk",
  MUSIC = "Musikk",
  PE = "Kroppsøving",
  RELIGION = "Religion",
  TECHNOLOGY = "Teknologi",
  FOREIGN_LANGUAGE = "Fremmedspråk",

  PHYSICS = "Fysikk",
  CHEMISTRY = "Kjemi",
  BIOLOGY = "Biologi",
  ECONOMICS = "Økonomi",
  ECONOMY_AND_LEADERSHIP = "Økonomi og ledelse",
  COMPUTER_SCIENCE = "Informasjonsteknologi",
  HOME_ECONOMICS = "Mat og helse",
  GEOGRAPHY = "Geografi",
  HISTORY = "Historie",
  POLITICS = "Politikk og menneskerettigheter",
  PSYCHOLOGY = "Psykologi",
  SOCIOLOGY = "Sosiologi",
  PHILOSOPHY = "Filosofi",
  FRENCH = "Fransk",
  SPANISH = "Spansk",
  GERMAN = "Tysk",

  ELECTRO = "Elektro",
  BUILDING_CONSTRUCTION = "Bygg- og anleggsteknikk",
  HEALTH_CHILDCARE = "Helse- og oppvekstfag",
  MEDIA_COMMUNICATION = "Medier og kommunikasjon",
  DESIGN_CRAFT = "Design og håndverk",
  TECHNOLOGY_INDUSTRY = "Teknologi- og industrifag",
  SERVICE_COMMUNICATION = "Service og samferdsel",
  AGRICULTURE_FOOD = "Naturbruk og matproduksjon",
}

export const allSubjects: Subject[] = Object.values(Subject);